version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"             # Root directory of the repository
    schedule:
      interval: "daily"        # Dependabot checks for updates daily
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    reviewers:
      - AuraFrameFx-Gen        # Replace with actual reviewers if needed
    labels:
      - "dependencies"
      - "gradle"
